from .team import TeamNestedSerializer, TeamListSerializer, TeamDetailSerializer, TeamPostSerializer
from .location import LocationNestedSerializer, LocationListSerializer, LocationDetailSerializer, LocationPostSerializer
from .player import PlayerNestedSerializer, PlayerListSerializer, PlayerDetailSerializer, PlayerPostSerializer
from .event import EventNestedSerializer, EventListSerializer, EventDetailSerializer, EventPostSerializer
