from rest_framework.serializers import Serializer, CharField


class DaDataCitySerializer(Serializer):
    postal_code = CharField(source='data.postal_code')
    country = CharField(source='data.country')
    region_fias_id = CharField(source='data.region_fias_id')
    region_with_type = CharField(source='data.region_with_type')
    area_fias_id = CharField(source='data.area_fias_id')
    area_with_type = CharField(source='data.area_with_type')
    city_fias_id = CharField(source='data.city_fias_id')
    city_with_type = CharField(source='data.city_with_type')
    city = CharField(source='data.city')
    city_district_fias_id = CharField(source='data.city_district_fias_id')
    city_district_with_type = CharField(source='data.city_district_with_type')
    city_district = CharField(source='data.city_district')
    settlement_fias_id = CharField(source='data.settlement_fias_id')
    settlement_with_type = CharField(source='data.settlement_with_type')
    settlement = CharField(source='data.settlement')
    fias_id = CharField(source='data.fias_id')
    fias_level = CharField(source='data.fias_level')
    geo_lat = CharField(source='data.geo_lat')
    geo_lon = CharField(source='data.geo_lon')
    value = CharField()


class DaDataAddressSerializer(Serializer):
    postal_code = CharField(source='data.postal_code')
    country = CharField(source='data.country')
    region_fias_id = CharField(source='data.region_fias_id')
    region_with_type = CharField(source='data.region_with_type')
    area_fias_id = CharField(source='data.area_fias_id')
    area_with_type = CharField(source='data.area_with_type')
    city_fias_id = CharField(source='data.city_fias_id')
    city_with_type = CharField(source='data.city_with_type')
    city = CharField(source='data.city')
    city_district_fias_id = CharField(source='data.city_district_fias_id')
    city_district_with_type = CharField(source='data.city_district_with_type')
    city_district = CharField(source='data.city_district')
    settlement_fias_id = CharField(source='data.settlement_fias_id')
    settlement_with_type = CharField(source='data.settlement_with_type')
    settlement = CharField(source='data.settlement')
    street_fias_id = CharField(source='data.street_fias_id')
    street_with_type = CharField(source='data.street_with_type')
    street = CharField(source='data.street')
    house_fias_id = CharField(source='data.house_fias_id')
    house_type = CharField(source='data.house_type')
    house = CharField(source='data.house')

    fias_id = CharField(source='data.fias_id')
    fias_level = CharField(source='data.fias_level')
    geo_lat = CharField(source='data.geo_lat')
    geo_lon = CharField(source='data.geo_lon')
    value = CharField()
