name: Django-app workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # Выполняет деплой
          cd /var/www/api-dev/
          source venv/bin/activate
          cd ftc/
          git pull
          python manage.py makemigrations
          python manage.py migrate
          service gunicorn restart
          service nginx restart
